config/routes.rb
Obscura::Application.routes.draw do
  
  resources :posts

  root to: 'static_pages#home'

  match '/tutorials',   to: 'posts#index'
  match '/contact',     to: 'static_pages#contact'
  match '/downloads',   to: 'static_pages#downloads' #get "static_pages/downloads" when using relative paths. 
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
  validates_presence_of :body, :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

   http_basic_authenticate_with :name => "jpadv", :password => "secret blog titan", :except => [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end


  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def tutorials
  end

  def contact
  end

  def downloads
  end
end

app/helpers/application_helper.rb
require 'open-uri'

module ApplicationHelper

  attr_accessor :gravinfo
	#Returns whether there is a costume page title.			#Comment or Documentation
	def full_title(page_title)								#Method definition
		base_title = "Obscura"									#Variable definition
		if page_title.empty?									#Boolean test
			base_title												#Implicit return
		else
			"#{base_title} | #{page_title}"							#String interpolation
		end														#End of Boolean test
	end 													#End of method definition

	def gravatar_pro
    #Insert your email 
    user = 'jose.padilla.88@gmail.com'
    options = { size: 175 }
  	gravatar_id = Digest::MD5::hexdigest(user.downcase)
  	size = options[:size]
  	gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  	image_tag(gravatar_url, alt: user, class: "gravatar")
  end

  def gravatar_info
    #Insert your email
    user = 'jose.padilla.88@gmail.com'
  	gravatar_id = Digest::MD5::hexdigest(user.downcase)
  	gravatar_url = "https://secure.gravatar.com/#{gravatar_id}.xml"
  	@gravinfo = ActiveSupport::XmlMini.parse(OpenURI.open_uri(gravatar_url).read)
  end

  def getName
    html = ""
    html << "<b>" << gravinfo["response"]["entry"]["name"]["formatted"]["__content__"] << "</b>" << "<br>"
  end

  def getAboutMe
    html = ""
    html << gravinfo["response"]["entry"]["aboutMe"]["__content__"] << "<br>"
  end

  def getLocation
    html = ""
    html << gravinfo["response"]["entry"]["currentLocation"]["__content__"] << "<br>"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav>
		<!--Add awesome links here! -->
	</nav>
	<small>
		<p>
		 Website created using Ruby on Rails. Slidheshow created with SlidesJS. Some effects created
		 by using fancybox, css and javascript.
		</p>
		<p>
			<small>
				2012 &copy Jose Padilla
			</small>
		</p>
	</small>
</footer>

app/views/layouts/_header.html.erb
<header class="nav-bar">	
	<div class="nav-inner">
		<%= link_to "Obscura", root_path, class:"nav-btn", id: "logo"%>
		<div class="nav-container">
			<ul>
				<li><%= link_to "Home", root_path, class: "nav-btn", id: "nav-hom" %></li>
				<li><%= link_to "Tutorials", tutorials_path, class: "nav-btn", id: "nav-tut"%></li>
				<li><%= link_to "Downloads", downloads_path, class: "nav-btn", id: "nav-dwn" %></li>
				<li><%= link_to "Contact", contact_path, class: "nav-btn"%></li>
			</ul>
		</div>
	</div>
</header>

app/views/layouts/_shin.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!--[if !IE 7]>
	<style type="text/css">
		#wrap {display:table;height:100%}
	</style>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>
  			<%= full_title(yield(:title)) %>
  		</title>
  		<%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Oxygen:400,700" %>
  		<%= stylesheet_link_tag    "application", :media => "all" %>
  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>
  		<%= render 'layouts/shin' %>
	</head>
	
	<!-- The main body of the website -->
	<body>
		<!-- The main header of the site. -->
		<%= render 'layouts/header' %>
		<!-- A container that holds the contents of the site. -->
		<div class='container'>
			<div class='box'>
				<div class='break'></div>
				<div class="main">
					<div class="box_container">
						<%= yield %>
					</div>
				</div>
			</div>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Tutorials</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/posts/new.html.erb
<h1>New post</h1>

<div id='formStyle'>
	<%= render 'form' %>

	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'My Card') %>
<canvas id='canvaSquare' data-shape="circle">
	Canvas not supported in your browser.
</canvas>

<div class='flip'>
	<div class='card'>
		<div class='face front'>
			<div id='mylogo'>
				<%= gravatar_pro() %>
			</div>
			<div id='info'>
					<%=  gravatar_info()
					getName().html_safe %>
					<b>About: </b><%= getAboutMe().html_safe %>
					<b>Location: </b><%= getLocation().html_safe %>
			</div>
			<small>
				!
			</small>
			<div id="backInfo">
				<%= getAboutMe().html_safe %>
			</div>
		</div>
		<div class='face back'>
			<div id='reachMetext'>
				Can be reached here as well.
			</div>
			<ul>
				<li><%= link_to image_tag("contact_logos/fbook.png", size:"85x105", alt:"Facebook", id:"fbook"), 
					"http://www.facebook.com/jose.padilla"%></li>
				<li><%= link_to image_tag("contact_logos/twitter.png", size:"115x105", alt:"Twitter", id:"twitter"), 
					"http://www.twitter.com/jpad_ii"%></li>
				<li><%= link_to image_tag("contact_logos/dbart.png", size:"115x105", alt:"DeviantArt", id:"dbart"), 
					"http://jpadv.deviantart.com"%></li>
				<li><%= link_to image_tag("contact_logos/gplus.png", size:"115x105", alt:"Google+", id:"gplus"), 
					"http://plus.google.com/110872379653084269780"%></li>
				<li><%= link_to image_tag("contact_logos/github.png", size:"115x105", alt:"Github", id:"github"), 
					"http://www.github.com/jpadv"%></li>
			</ul>
			<small>
				Flip me again!
			</small>
		</div>
	</div>
</div>

app/views/static_pages/downloads.html.erb
<% provide(:title, 'Downloads') %>
<h1>Downloads</h1>
<p>			
	This will be the downloads page.
</p>

app/views/static_pages/home.html.erb
<canvas id='canvaSquare' data-shape='square'>
	Canvas not supported in your browser.
</canvas>

<div id="slides">
	<%= link_to "<", "#", class: "prev", alt: "Arrow Prev" %>
	<%= link_to ">", "#", class: "next", alt: "Arrow Next" %>
	<div class="slides_container">
		<%= link_to image_tag("img/slide-1.jpg", size: "900x420", alt: "Slide 1"), "/assets/img/slide-1.jpg", class: "fancy", rel: "homegallery", target: "_blank", title: "Jose Padilla | The Rock @ Alcatraz" %>

		<%= link_to image_tag("img/slide-2.jpg", size: "900x420", alt: "Slide 2"), "/assets/img/slide-2.jpg", class: "fancy", rel: "homegallery", target: "_blank", title: "Jose Padilla | The Tower @ Alcatraz" %>

		<%= link_to image_tag("img/slide-3.jpg", size: "900x420", alt: "Slide 3"), "/assets/img/slide-3.jpg",  class: "fancy", rel: "homegallery", target: "_blank", title: "Jose Padilla | Bye @ Alcatraz" %>

		<%= link_to image_tag("img/slide-4.jpg", size: "900x420", alt: "Slide 4"), "/assets/img/slide-4.jpg",  class: "fancy", rel: "homegallery", target: "_blank", title: "Jose Padilla | SF Giants Practice" %>

		<%= link_to image_tag("img/slide-5.jpg", size: "900x420", alt: "Slide 5"), "/assets/img/slide-5.jpg", class: "fancy", rel: "homegallery", target: "_blank", title: "Jose Padilla | The Dr. Marthin Lurther King Library @ San Jose" %>

		<%= link_to image_tag("img/slide-6.jpg", size: "900x420", alt: "Slide 6"), "/assets/img/slide-6.jpg", class: "fancy", rel: "homegallery", targe: "_blank", title: "Jose Padill | Your wishing is my COMMAND" %>

		<%= link_to image_tag("img/slide-7.jpg", size: "900x420", alt: "Slide 7"), "/assets/img/slide-7.jpg", class: "fancy", rel: "homegallery", target: "_blank", title: "Jose Padilla | Strawberry Plant" %>
	</div>
</div>